[project]
name = "searxng-mcp-server"
version = "0.1.0"
description = "Model Control Protocol (MCP) server for SearXNG search engine"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.2.0",
]

[project.scripts]
searxng-mcp-server = "server:main"